[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "graphenee"
authors = [{name = "Farukh Ijaz", email = "fijaz@octans.ai"}]
dynamic = ["version", "description"]
